name = "North Hole Pack"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a40d498e1b5560cf90f2128bc5b797ce97fa708d2b59246a7fce49333ed9eba3"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
