name = "North Hole Pack"
version = "1.1.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ffa84bde8deff639a9d1ae612918fb885197d3bcc27e1e8e0434d46c821ddd9"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
