name = "North Hole Pack"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf246dffe8b6dc2f2ac80e867a3622d8b8e00d492fc8465294ac781b809817b3"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
