name = "North Hole Pack"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac444660f3231fc26aa66925817cc7ec9a0f5f2c995bdfc4104cec03c76faa4d"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
