name = "North Hole Pack"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "832f12b2707011eb960f950c234f30cde7a3a2d5c6fe9aaa889831769b746069"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
